changelog:
  categories:
    - title: Features
      labels:
        - enhancement
    - title: Bug fixes
      labels:
        - bug
    - title: Refactors
      labels:
        - refactor
    - title: Documentation
      labels:
        - documentation
    - title: Maintenance
      labels:
        - chore
        - ci
  exclude:
    labels:
      - skip-changelog
